name: Analysis & Coverage

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    types: [opened, synchronize]

  push:
    branches: [main]

jobs:
  dart_analysis:
    if: ${{ github.repository_owner == 'kekavc24' }}
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ Hello Git
        uses: actions/checkout@v4

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: ğŸ§¹ Run formatter
        working-directory: ${{ github.workspace }}
        run: |
          dart pub get
          dart format --output=none --set-exit-if-changed .

      - name: ğŸ” Analyze
        working-directory: ${{ github.workspace }}
        run: dart analyze --fatal-infos

  test_and_gen_coverage:
    runs-on: ubuntu-latest
    needs: dart_analysis

    steps:
      - name: ğŸ Hello Git
        uses: actions/checkout@v4

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: ğŸ§ª Run tests with coverage ğŸ“‘
        run: |
          dart pub get
          dart run coverage:test_with_coverage --scope-output lib/

      - name: ğŸ›« Track coverage
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          file: "${{ github.workspace }}/coverage/lcov.info"
