name: Analysis, Test & Coverage

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          sync-labels: true

  testing:
    if: ${{ github.repository_owner == 'kekavc24'}}
    needs: labeler
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ Hello Git
        uses: actions/checkout@v5

      - name: Hello Bot
        uses: ./.github/actions/configure_bot
      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: ğŸ§¹ Run formatter
        working-directory: ${{ github.workspace }}
        run: |
          dart pub get
          dart format --output=none --set-exit-if-changed .

      - name: ğŸ” Analyze
        working-directory: ${{ github.workspace }}
        run: dart analyze --fatal-infos

      - name: Package Filter
        id: filter
        uses: ./.github/actions/package_filter
        with:
          bot-token: ${{ secrets.BOT_KEY }}
          working-directory: ${{ github.workspace }}
          pr: ${{ github.event.pull_request.number }}
