name: Analysis & Coverage

on:
  workflow_run:
    workflows: [label_pr]
    types: [completed]

  workflow_dispatch:

  pull_request_target:
    branches: [main]
    types: [opened, synchronize]

  push:
    branches: [main]

jobs:
  testing:
    if: ${{ github.repository_owner == 'kekavc24' }}
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ Hello Git
        uses: actions/checkout@v5

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: ğŸ§¹ Run formatter
        working-directory: ${{ github.workspace }}
        run: |
          dart pub get
          dart format --output=none --set-exit-if-changed .

      - name: ğŸ” Analyze
        working-directory: ${{ github.workspace }}
        run: dart analyze --fatal-infos

      - name: ğŸ“¤ Package Filter
        id: package
        working-directory: ${{ github.workspace }}
        env:
          GH_TOKEN: ${{ secrets.BOT_KEY }}
        run: |
          git config --global user.email "143215479+Kavisi-bot@users.noreply.github.com"
          git config --global user.name "Kavisi-bot"
          cd scripts
          pwd

          filtered=$(dart package_filter.dart \
            --pr "${{ github.event.pull_request.number }}"
            --working-directory "${{ github.workspace }}"
            --labels "${{ toJson(github.event.pull_request.labels.*.name) }}")

          echo "package=$filtered" >> "$GITHUB_OUTPUT"

      - name: ğŸ§ª Run tests with coverage ğŸ“‘
        if: ${{ steps.package.outputs.package != 'Naught' }}
        working-directory: ${{ steps.package.outputs.package }}
        run: |
          dart pub get
          dart run coverage:test_with_coverage

      - name: ğŸ›« Track coverage
        if: ${{ steps.package.outputs.package != 'Naught' }}
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ github.token }}
          file: "${{ steps.package.outputs.package }}/coverage/lcov.info"
          format: lcov

      - name: ğŸƒğŸ½ Run test suite, ğŸ’¬ Add PR comment
        if: ${{ contains(steps.package.outputs.package, 'rookie_yaml') }}
        id: runner
        env:
          GH_TOKEN: ${{ secrets.BOT_KEY }}
        run: |
          dart pub get
          cd scripts
          pwd
          dart test_suite_comment.dart \
            --pr ${{ github.event.pull_request.number }} \
            --tip-SHA ${{ github.event.pull_request.head.sha }} \
            --working-directory ${{ steps.package.outputs.package }}
