name: Analysis, Test & Coverage

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          sync-labels: true

  testing:
    if: ${{ github.repository_owner == 'kekavc24'}}
    needs: labeler
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ Hello Git
        uses: actions/checkout@v5

      - name: Hello Bot
        uses: ./.github/actions/configure_bot
      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: ğŸ§¹ Run formatter
        working-directory: ${{ github.workspace }}
        run: |
          dart pub get
          dart format --output=none --set-exit-if-changed .

      - name: ğŸ” Analyze
        working-directory: ${{ github.workspace }}
        run: dart analyze --fatal-infos

      - name: Package Filter
        id: filter
        uses: ./.github/actions/package_filter
        with:
          bot-token: ${{ secrets.BOT_KEY }}
          working-directory: ${{ github.workspace }}
          pr: ${{ github.event.pull_request.number }}

      - name: Run Tests
        if: ${{ steps.filter.outputs.package-name != 'Naught' }}
        uses: ./.github/actions/test_runner
        with:
          bot-token: ${{ secrets.BOT_KEY }}
          pr: ${{ github.event.pull_request.number }}
          pr-SHA: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ github.token }}
          package-name: ${{ steps.filter.outputs.package-name }}
          package-directory: "${{ github.workspace }}/packages/${{ steps.filter.outputs.package-name }}"

      - name: Run YAML Test Suite
        if: ${{ steps.filter.outputs.package-name == 'rookie_yaml' }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.BOT_KEY }}
        run: |
          dart pub get
          cd scripts
          pwd

          dart test_suite_comment.dart \
            --pr ${{ github.event.pull_request.number }} \
            --tip-SHA ${{ github.event.pull_request.head.sha }} \
            --working-directory "${{ github.workspace }}"
